# Generated by Django 3.2.12 on 2022-03-24 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openimage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
